#############################################################################
# Makefile for building: musickit.app/Contents/MacOS/musickit
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Mar 22 18:02:31 2010
# Project:  musickit.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile musickit.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_PHONON_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.6/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/usr/include/QtNetwork -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/usr/include/QtXml -I/Library/Frameworks/phonon.framework/Versions/4/Headers -I/usr/include/phonon -I/Library/Frameworks/QtWebKit.framework/Versions/4/Headers -I/usr/include/QtWebKit -I/usr/include -Iqplaydarclient/include -I/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Headers -I/usr/include/phonon_compat -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch i386
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -L/usr/local/lib -lqjson -framework JavaVM -framework QtWebKit -framework QtXmlPatterns -framework phonon -framework QtDBus -framework QtXml -framework QtGui -framework QtNetwork -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		WebkitApi.cpp \
		qplaydarclient/src/query.cpp \
		qplaydarclient/src/result.cpp \
		qplaydarclient/src/client.cpp \
		player/playengine.cpp \
		spoon/SpoonCore.cpp \
		spoon/JavaBridge.cpp moc_mainwindow.cpp \
		moc_WebkitApi.cpp \
		moc_client.cpp \
		moc_query.cpp \
		moc_result.cpp \
		moc_playengine.cpp \
		moc_SpoonCore.cpp
OBJECTS       = main.o \
		mainwindow.o \
		WebkitApi.o \
		query.o \
		result.o \
		client.o \
		playengine.o \
		SpoonCore.o \
		JavaBridge.o \
		moc_mainwindow.o \
		moc_WebkitApi.o \
		moc_client.o \
		moc_query.o \
		moc_result.o \
		moc_playengine.o \
		moc_SpoonCore.o
DIST          = /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		musickit.pro
QMAKE_TARGET  = musickit
DESTDIR       = 
TARGET        = musickit.app/Contents/MacOS/musickit

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile musickit.app/Contents/PkgInfo musickit.app/Contents/Resources/empty.lproj musickit.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) musickit.app/Contents/MacOS/ || $(MKDIR) musickit.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: musickit.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtWebKit.framework/QtWebKit.prl \
		/Library/Frameworks/phonon.framework/phonon.prl \
		/Library/Frameworks/QtDBus.framework/QtDBus.prl \
		/Library/Frameworks/QtXml.framework/QtXml.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtXmlPatterns.framework/QtXmlPatterns.prl \
		/Library/Frameworks/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile musickit.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.6/mkspecs/features/debug.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtWebKit.framework/QtWebKit.prl:
/Library/Frameworks/phonon.framework/phonon.prl:
/Library/Frameworks/QtDBus.framework/QtDBus.prl:
/Library/Frameworks/QtXml.framework/QtXml.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtXmlPatterns.framework/QtXmlPatterns.prl:
/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile musickit.pro

musickit.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) musickit.app/Contents || $(MKDIR) musickit.app/Contents 
	@$(DEL_FILE) musickit.app/Contents/PkgInfo
	@echo "APPL????" >musickit.app/Contents/PkgInfo
musickit.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) musickit.app/Contents/Resources || $(MKDIR) musickit.app/Contents/Resources 
	@touch musickit.app/Contents/Resources/empty.lproj
	
musickit.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) musickit.app/Contents || $(MKDIR) musickit.app/Contents 
	@$(DEL_FILE) musickit.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,musickit,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.6/mkspecs/macx-g++/Info.plist.app >musickit.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/musickit1.0.0 || $(MKDIR) .tmp/musickit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/musickit1.0.0/ && $(COPY_FILE) --parents mainwindow.h WebkitApi.h qplaydarclient/include/qplaydar.h qplaydarclient/include/qplaydar/client.h qplaydarclient/include/qplaydar/query.h qplaydarclient/include/qplaydar/result.h player/playengine.h spoon/SpoonCore.h spoon/JavaBridge.h .tmp/musickit1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp WebkitApi.cpp qplaydarclient/src/query.cpp qplaydarclient/src/result.cpp qplaydarclient/src/client.cpp player/playengine.cpp spoon/SpoonCore.cpp spoon/JavaBridge.cpp .tmp/musickit1.0.0/ && (cd `dirname .tmp/musickit1.0.0` && $(TAR) musickit1.0.0.tar musickit1.0.0 && $(COMPRESS) musickit1.0.0.tar) && $(MOVE) `dirname .tmp/musickit1.0.0`/musickit1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/musickit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r musickit.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_WebkitApi.cpp moc_client.cpp moc_query.cpp moc_result.cpp moc_playengine.cpp moc_SpoonCore.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_WebkitApi.cpp moc_client.cpp moc_query.cpp moc_result.cpp moc_playengine.cpp moc_SpoonCore.cpp
moc_mainwindow.cpp: player/playengine.h \
		WebkitApi.h \
		mainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_WebkitApi.cpp: player/playengine.h \
		WebkitApi.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ WebkitApi.h -o moc_WebkitApi.cpp

moc_client.cpp: qplaydarclient/include/qplaydar/client.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qplaydarclient/include/qplaydar/client.h -o moc_client.cpp

moc_query.cpp: qplaydarclient/include/qplaydar/query.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qplaydarclient/include/qplaydar/query.h -o moc_query.cpp

moc_result.cpp: qplaydarclient/include/qplaydar/result.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qplaydarclient/include/qplaydar/result.h -o moc_result.cpp

moc_playengine.cpp: player/playengine.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ player/playengine.h -o moc_playengine.cpp

moc_SpoonCore.cpp: spoon/JavaBridge.h \
		spoon/SpoonCore.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ spoon/SpoonCore.h -o moc_SpoonCore.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		player/playengine.h \
		WebkitApi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		player/playengine.h \
		WebkitApi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

WebkitApi.o: WebkitApi.cpp WebkitApi.h \
		player/playengine.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WebkitApi.o WebkitApi.cpp

query.o: qplaydarclient/src/query.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o query.o qplaydarclient/src/query.cpp

result.o: qplaydarclient/src/result.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o result.o qplaydarclient/src/result.cpp

client.o: qplaydarclient/src/client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o qplaydarclient/src/client.cpp

playengine.o: player/playengine.cpp player/playengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playengine.o player/playengine.cpp

SpoonCore.o: spoon/SpoonCore.cpp spoon/SpoonCore.h \
		spoon/JavaBridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpoonCore.o spoon/SpoonCore.cpp

JavaBridge.o: spoon/JavaBridge.cpp spoon/JavaBridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JavaBridge.o spoon/JavaBridge.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_WebkitApi.o: moc_WebkitApi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WebkitApi.o moc_WebkitApi.cpp

moc_client.o: moc_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_client.o moc_client.cpp

moc_query.o: moc_query.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_query.o moc_query.cpp

moc_result.o: moc_result.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_result.o moc_result.cpp

moc_playengine.o: moc_playengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playengine.o moc_playengine.cpp

moc_SpoonCore.o: moc_SpoonCore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SpoonCore.o moc_SpoonCore.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

